`match.arg` source code

```{r}
match.arg <- function(arg, choices, several.ok = FALSE) {
  if (missing(choices)) {
    # get the formal(default) arguments
    # of the calling function
    # returns a pairlist
    formal.args <- formals(sys.function(sysP <- sys.parent()))
    # evaluates the formal.args and returns a character vector containing
    # c("mess", "cake", "hyuuge mistake")
    choices <- eval(formal.args[[as.character(substitute(arg))]],
      envir = sys.frame(sysP)
    )
  }
  if (is.null(arg)) {
    return(choices[1L])
  } else if (!is.character(arg)) {
    stop("'arg' must be NULL or a character vector")
  }
  # when several.ok = FALSE
  if (!several.ok) { # most important (default) case:
    ## the arg can be the whole of choices as a default argument.
    # execution stops here if args and choices are identical in our case.
    # e.g., make_something()
    if (identical(arg, choices)) {
      return(arg[1L])
    }
    if (length(arg) > 1L) stop("'arg' must be of length 1")
  } else if (length(arg) == 0L) stop("'arg' must be of length >= 1")

  ## handle each element of arg separately
  # get the indices of the matching choices (from the choices argument)
  # e.g., for arg = mess, i = 1, for arg = cake, i = 2
  # e.g., for arg = c("mess", "cake"), i = c(1, 2)
  i <- pmatch(arg, choices, nomatch = 0L, duplicates.ok = TRUE)
  if (all(i == 0L)) {
    stop(gettextf(
      "'arg' should be one of %s",
      paste(dQuote(choices), collapse = ", ")
    ),
    domain = NA
    )
  }
  i <- i[i > 0L]
  if (!several.ok && length(i) > 1) {
    stop("there is more than one match in 'match.arg'")
  }
  # vector containing the matched arguments
  choices[i]
}
```

```{r}
make_something <- function(something = c("mess", "cake", "hyuuge mistake")) {
  # something = c("mess", "cake", "hyuuge mistake") by default
  something <- match.arg(something)
  message("I made a ", something, ".\n")
}
debugonce(match.arg)
make_something(c("cake", "mess"))
```
